#+TITLE: Syllabus for CSE215: Foundations of Computer Science (Spring 2022)
#+HTML_HEAD_EXTRA: <style>span[class^="section-number-"]:after { content: '.'; }</style>

* Overview
This course is  offered by the CS Department of SUNY Korea. This repository is publicly accessible and hosts the courseware that will be added incrementally along the semester.  The courseware is adapted from the ones used in Stony Brook University.

* Prerequisites
AMS 151 or MAT 125 or MAT 131
* Instructor 
Zhoulai Fu (zhoulai.fu@sunykorea.ac.kr, www.zhoulaifu.com)
* Schedule
TBA

* Course Description
In this course, we will learn the part of mathematics, also know as discrete math,  which is required in well understanding computer science. The course  covers the following topics: 
logic (propositional logic and predicate logic), number theory, proof
techniques, sequences, recursion, functions, relations, and sets.

* Course objectives
The students should gain the following knowledge and skills:
- An ability to check if a mathematical argument is valid (i.e., logical) and sound (i.e., truthful)
- AXn ability to verify the correctness of proofs of some existing theorems and prove some new theorems
- An ability to use the mathematical concepts of sequences, functions, relations, and sets in solving computing problems

* Textbook
Discrete Mathematics: Introduction to Mathematical Reasoning. Susanna S. Epp. 1st Edition


* Grading
- Assignments: 30% 
- Midterms: 40%
- Final exam: 30%

* Policy on lateness
Late assignments will generally not be accepted. Exceptional requests must be presented to the course instructor with supporting documentation as soon as possible.

* Disabilities Act

If you have a physical, psychological, medical or learning disability that may impact your course work, please contact the Department of Student Affairs, Campus Building A, Room 207, (032) 626-1190. They will determine with you what accommodations, if any, are necessary and appropriate. All information and documentation is confidential.

* Academic Integrity

Each student must pursue his or her academic goals honestly and be personally accountable for all submitted work. Representing another person's work as your own is always wrong. Faculty members are required to report any suspected instances of academic dishonesty to the Academic Judiciary Committee or the Department of Academic Affairs, Campus Building A, Room 201, (032) 626-1121.

* Critical Incident Management

SUNY Korea expects students to respect the rights,
privileges, and property of other people. Faculty are required to report to the Department of Academic Affairs any disruptive behavior that interrupts their ability to teach, compromises the safety of the learning environment, or inhibits students' ability to learn.
